### ISSUE TITLE
Abschlussscreen einbauen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2016-semaphore#94]
Hi,

nach der Quizrunde muss ja noch der Abschlussscreen kommen. Da bitte zeitnah zwischen der Logiktruppe und den zusammenführern klären wer das macht. Es wäre gut, wenn das bis Montag gemacht wäre, damit die Endscreen Leute dann im richtigen Kontext ihren Screen fein machen können. Also bitte dem Team entsprechend Bescheid sagen, wenn das verfügbar ist.

**Comment by mariofaske** [comment]
Ich sitze gerade am Endscreen. Wird heute, spätestens morgen Abend fertig sein.

**Comment by TimSchuerheck** [comment]
Hey, wir sollten mal Skypen. Wenn du Zeit hast. Du findest mich dort unter Tim Schürheck. Grüße 

Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Mario Faske <notifications@github.com> Datum: 12.11.16  17:50  (GMT+01:00) An: th-koeln/wba1-2016-semaphore <wba1-2016-semaphore@noreply.github.com> Cc: TimSchuerheck <steinreinfein@googlemail.com>, Assign <assign@noreply.github.com> Betreff: Re: [th-koeln/wba1-2016-semaphore] Abschlussscreen einbauen (#94) 
Ich sitze gerade am Endscreen. Wird heute, spätestens morgen Abend fertig sein.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/th-koeln/wba1-2016-semaphore","title":"th-koeln/wba1-2016-semaphore","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/th-koeln/wba1-2016-semaphore"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mariofaske in #94: Ich sitze gerade am Endscreen. Wird heute, spätestens morgen Abend fertig sein."}],"action":{"name":"View Issue","url":"https://github.com/th-koeln/wba1-2016-semaphore/issues/94#issuecomment-260133306"}}}

**Comment by mariofaske** [comment]
Also der Endscreen inst eingebaut und wird auch ordentlich aufgebaut und eingebunden. 
TODO sind noch:
- Rang darstellen (nach Abgleich mit dem Ranking) [_werde ich heute/morgen erledigen_]
- Bälle richtig anzeigen je nach gegebener Antwort [_sollte ich bis donnerstag hinbekommen_]

Aber der Screen ist soweit eingebunden und kann "verfeinert" werden
